import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { History, Download, Eye, Users, IndianRupee, AlertTriangle } from 'lucide-react';
import api from '../../Services/api.js';
import { formatINR } from '../../Services/formatters.js';

const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

const statusColors = {
  Draft:    'var(--text-secondary)',
  Reviewed: 'var(--info)',
  Approved: 'var(--warning)',
  Released: 'var(--success)',
};

const PayrollHistory = () => {
  const [history, setHistory] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [expandedRun, setExpandedRun] = useState(null);
  const [runPaylines, setRunPaylines] = useState([]);
  const [paylinesLoading, setPaylinesLoading] = useState(false);

  useEffect(() => {
    (async () => {
      try {
        const data = await api.get('/payroll/run-history');
        setHistory(data);
      } catch (err) {
        setError('Failed to load payroll history. ' + (err.message || ''));
      } finally {
        setLoading(false);
      }
    })();
  }, []);

  const handleViewRun = async (run) => {
    if (expandedRun?.id === run.id) {
      setExpandedRun(null);
      setRunPaylines([]);
      return;
    }
    setExpandedRun(run);
    setPaylinesLoading(true);
    try {
      const data = await api.get(`/payroll/history?runId=${run.id}`);
      setRunPaylines(data);
    } catch (err) {
      console.error(err);
    } finally {
      setPaylinesLoading(false);
    }
  };

  const formatDate = (d) => d ? new Date(d).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—';

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }}>
      {/* Header */}
      <div style={{ marginBottom: '2rem' }}>
        <h1 style={{ fontSize: '1.75rem', fontWeight: 700, marginBottom: '0.4rem', display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <History size={26} /> Payroll History
        </h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem', margin: 0 }}>
          Full audit trail of all payroll runs across all periods and versions.
        </p>
      </div>

      {/* Error */}
      {error && (
        <div style={{ background: 'rgba(239,68,68,0.1)', border: '1px solid var(--danger)', color: 'var(--danger)', borderRadius: 'var(--radius-md)', padding: '0.85rem 1rem', marginBottom: '1.25rem', fontSize: '0.88rem' }}>
          <AlertTriangle size={15} style={{ marginRight: '0.5rem', verticalAlign: 'middle' }} />{error}
        </div>
      )}

      {/* Table */}
      <div style={{ background: 'var(--bg-secondary)', border: '1px solid var(--border-color)', borderRadius: 'var(--radius-lg)', overflow: 'hidden', boxShadow: 'var(--shadow-sm)' }}>
        {loading ? (
          <div style={{ textAlign: 'center', padding: '4rem', color: 'var(--text-secondary)' }}>Loading payroll history...</div>
        ) : history.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '4rem', color: 'var(--text-secondary)' }}>
            <History size={40} style={{ opacity: 0.2, marginBottom: '1rem' }} />
            <p style={{ fontSize: '0.9rem' }}>No payroll runs found.</p>
          </div>
        ) : (
          <div style={{ overflowX: 'auto' }}>
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.84rem' }}>
              <thead>
                <tr style={{ background: 'var(--bg-tertiary)', borderBottom: '1px solid var(--border-color)' }}>
                  {['Period', 'Version', 'Status', 'Employees', 'Net Amount', 'Generated By', 'Generated On', 'Released By', 'Released On', 'Actions'].map(h => (
                    <th key={h} style={{ padding: '0.75rem 1rem', textAlign: 'left', fontWeight: 600, color: 'var(--text-secondary)', whiteSpace: 'nowrap', fontSize: '0.78rem', textTransform: 'uppercase' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {history.map((run) => (
                  <>
                    <tr
                      key={run.id}
                      style={{
                        borderBottom: '1px solid var(--border-light)',
                        background: expandedRun?.id === run.id ? 'var(--bg-tertiary)' : 'transparent',
                        cursor: 'pointer', transition: 'background 0.15s'
                      }}
                      onClick={() => handleViewRun(run)}
                    >
                      <td style={{ padding: '0.85rem 1rem', fontWeight: 600, whiteSpace: 'nowrap' }}>
                        {MONTHS[run.month - 1]} {run.year}
                      </td>
                      <td style={{ padding: '0.85rem 1rem' }}>
                        <span style={{ padding: '2px 8px', background: 'var(--bg-tertiary)', border: '1px solid var(--border-color)', borderRadius: '12px', fontSize: '0.72rem', fontWeight: 700 }}>
                          v{run.version}
                        </span>
                      </td>
                      <td style={{ padding: '0.85rem 1rem' }}>
                        <span style={{
                          padding: '3px 8px', borderRadius: '10px', fontSize: '0.72rem', fontWeight: 700,
                          background: run.status === 'Released' ? 'rgba(16,185,129,0.12)' : run.status === 'Approved' ? 'rgba(245,158,11,0.12)' : 'rgba(100,116,139,0.1)',
                          color: statusColors[run.status] || 'var(--text-secondary)'
                        }}>{run.status}</span>
                      </td>
                      <td style={{ padding: '0.85rem 1rem' }}>
                        <span style={{ display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                          <Users size={13} style={{ opacity: 0.5 }} /> {run.totalEmployees}
                        </span>
                      </td>
                      <td style={{ padding: '0.85rem 1rem', fontWeight: 600, color: 'var(--accent-primary)' }}>
                        {run.totalAmount ? formatINR(run.totalAmount) : '—'}
                      </td>
                      <td style={{ padding: '0.85rem 1rem', color: 'var(--text-secondary)' }}>{run.generatedByName || '—'}</td>
                      <td style={{ padding: '0.85rem 1rem', color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>{formatDate(run.runDate)}</td>
                      <td style={{ padding: '0.85rem 1rem', color: 'var(--text-secondary)' }}>{run.releasedByName || '—'}</td>
                      <td style={{ padding: '0.85rem 1rem', color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>{formatDate(run.releasedAt)}</td>
                      <td style={{ padding: '0.85rem 1rem' }}>
                        <button
                          onClick={(e) => { e.stopPropagation(); handleViewRun(run); }}
                          style={{ display: 'inline-flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.75rem', color: 'var(--accent-primary)', background: 'none', border: 'none', cursor: 'pointer', fontWeight: 500, padding: '0.25rem 0.5rem', borderRadius: 'var(--radius-sm)' }}>
                          <Eye size={13} /> {expandedRun?.id === run.id ? 'Hide' : 'View'}
                        </button>
                      </td>
                    </tr>

                    {/* Expanded paylines */}
                    {expandedRun?.id === run.id && (
                      <tr key={`${run.id}-expanded`}>
                        <td colSpan={10} style={{ padding: 0, background: 'var(--bg-primary)', borderBottom: '2px solid var(--accent-primary)' }}>
                          <div style={{ padding: '1.25rem 1.5rem' }}>
                            <h4 style={{ fontSize: '0.9rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--text-secondary)' }}>
                              Pay Lines — {MONTHS[run.month - 1]} {run.year} v{run.version}
                              {run.status !== 'Released' && <span style={{ fontSize: '0.78rem', color: 'var(--warning)', marginLeft: '0.75rem' }}>(Read-only historical view)</span>}
                            </h4>
                            {paylinesLoading ? (
                              <div style={{ textAlign: 'center', padding: '1.5rem', color: 'var(--text-secondary)', fontSize: '0.85rem' }}>Loading pay lines...</div>
                            ) : runPaylines.length === 0 ? (
                              <div style={{ textAlign: 'center', padding: '1.5rem', color: 'var(--text-secondary)', fontSize: '0.85rem' }}>No pay lines found for this run.</div>
                            ) : (
                              <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.82rem' }}>
                                <thead>
                                  <tr style={{ background: 'var(--bg-tertiary)' }}>
                                    {['Employee', 'Days Paid', 'Gross', 'PF', 'PT', 'LOP', 'TDS', 'Net Salary', 'Status', 'Payslip'].map(h => (
                                      <th key={h} style={{ padding: '0.45rem 0.75rem', fontWeight: 600, color: 'var(--text-secondary)', fontSize: '0.72rem' }}>{h}</th>
                                    ))}
                                  </tr>
                                </thead>
                                <tbody>
                                  {runPaylines.map(line => (
                                    <tr key={line.payroll_id} style={{ borderBottom: '1px solid var(--border-light)' }}>
                                      <td style={{ padding: '0.5rem 0.75rem', fontWeight: 500 }}>{line.employee_name}</td>
                                      <td style={{ padding: '0.5rem 0.75rem', textAlign: 'center' }}>{line.employee_working_days}/{line.monthly_working_days}</td>
                                      <td style={{ padding: '0.5rem 0.75rem' }}>{formatINR(line.total_earnings)}</td>
                                      <td style={{ padding: '0.5rem 0.75rem' }}>{formatINR(line.pf)}</td>
                                      <td style={{ padding: '0.5rem 0.75rem' }}>{formatINR(line.pt)}</td>
                                      <td style={{ padding: '0.5rem 0.75rem' }}>{formatINR(line.lop)}</td>
                                      <td style={{ padding: '0.5rem 0.75rem' }}>{formatINR(line.deductions - (line.pf || 0) - (line.pt || 0) - (line.lop || 0))}</td>
                                      <td style={{ padding: '0.5rem 0.75rem', fontWeight: 700, color: 'var(--accent-primary)' }}>{formatINR(line.net_salary)}</td>
                                      <td style={{ padding: '0.5rem 0.75rem' }}>
                                        <span style={{ padding: '2px 6px', borderRadius: '4px', fontSize: '0.68rem', fontWeight: 600, background: line.payment_status === 'Paid' ? 'rgba(16,185,129,0.12)' : 'rgba(239,68,68,0.1)', color: line.payment_status === 'Paid' ? 'var(--success)' : 'var(--danger)' }}>
                                          {line.payment_status}
                                        </span>
                                      </td>
                                      <td style={{ padding: '0.5rem 0.75rem' }}>
                                        <a href={`/api/payroll/payslips/${line.payroll_id}/download`} target="_blank" rel="noreferrer"
                                          style={{ display: 'inline-flex', alignItems: 'center', gap: '0.25rem', fontSize: '0.73rem', color: 'var(--accent-primary)', textDecoration: 'none', fontWeight: 500 }}>
                                          <Download size={11} /> PDF
                                        </a>
                                      </td>
                                    </tr>
                                  ))}
                                </tbody>
                              </table>
                            )}
                          </div>
                        </td>
                      </tr>
                    )}
                  </>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </motion.div>
  );
};

export default PayrollHistory;
