-- ==================================================
-- NEXUS HRMS: TARGET POSTGRESQL DATABASE SCHEMA (SPIKE)
-- ==================================================

-- Recreate schema clean
DROP SCHEMA IF EXISTS dbo CASCADE;
CREATE SCHEMA dbo;

-- 1. CREATE LOOKUP & MASTER TABLES

-- CompanySettings Table
CREATE TABLE dbo.CompanySettings (
    SettingID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CompanyName VARCHAR(150) NOT NULL,
    CompanyAddress VARCHAR(250) NULL,
    CompanyPAN VARCHAR(20) NULL,
    CompanyGST VARCHAR(20) NULL,
    PFNumber VARCHAR(30) NULL,
    ESINumber VARCHAR(30) NULL,
    PayrollProcessingDay INT NOT NULL DEFAULT 25,
    SalaryCreditDay INT NOT NULL DEFAULT 1,
    ContactNumber VARCHAR(30) NULL,
    SupportEmail VARCHAR(100) NULL,
    CompanyLogo VARCHAR(255) NULL
);

-- HolidayMaster Table
CREATE TABLE dbo.HolidayMaster (
    HolidayID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    HolidayName VARCHAR(100) NOT NULL,
    HolidayDate DATE NOT NULL UNIQUE,
    HolidayType VARCHAR(30) NOT NULL CHECK (HolidayType IN ('National', 'Regional', 'Optional')),
    IsOptional BOOLEAN NOT NULL DEFAULT FALSE
);

-- PayrollCalendar Table
CREATE TABLE dbo.PayrollCalendar (
    PayrollCalendarID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PayrollMonth INT NOT NULL,
    PayrollYear INT NOT NULL,
    AttendanceCutoffDate DATE NOT NULL,
    PayrollProcessingDate DATE NOT NULL,
    SalaryCreditDate DATE NOT NULL,
    LockDate DATE NOT NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT UQ_PayrollCalendar_Month_Year UNIQUE (PayrollMonth, PayrollYear)
);

-- Departments Table
CREATE TABLE dbo.Departments (
    DepartmentID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DepartmentName VARCHAR(100) NOT NULL UNIQUE,
    ManagerEmpID INT NULL
);

-- Designations Table
CREATE TABLE dbo.Designations (
    DesignationID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DesignationName VARCHAR(100) NOT NULL UNIQUE,
    Description VARCHAR(255) NULL
);

-- LeavePolicies Table
CREATE TABLE dbo.LeavePolicies (
    PolicyID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    LeaveType VARCHAR(50) NOT NULL UNIQUE CHECK (LeaveType IN ('Sick Leave', 'Casual Leave', 'Earned Leave', 'Maternity Leave', 'Paternity Leave', 'Unpaid Leave')),
    MaxAllowedDays INT NOT NULL DEFAULT 0,
    IsCarryForward BOOLEAN NOT NULL DEFAULT FALSE
);

-- 2. CREATE ROSTER TABLES

-- EmployeeMaster Table
CREATE TABLE dbo.EmployeeMaster (
    EmpID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    FirstName VARCHAR(40) NOT NULL,
    LastName VARCHAR(40) NOT NULL,
    DOJ DATE NOT NULL DEFAULT CURRENT_DATE,
    Designation VARCHAR(200) NULL,
    Department VARCHAR(100) NULL,
    EmpStatus VARCHAR(20) NOT NULL DEFAULT 'Active' 
        CHECK (EmpStatus IN ('Active', 'Inactive', 'On Notice', 'Resigned', 'Terminated', 'Retired')),
    DepartmentID INT NULL REFERENCES dbo.Departments(DepartmentID),
    DesignationID INT NULL REFERENCES dbo.Designations(DesignationID),
    IsPayrollEligible BOOLEAN NOT NULL DEFAULT TRUE
);

-- EmployeeDetails Table
CREATE TABLE dbo.EmployeeDetails (
    EmpID INT PRIMARY KEY REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    FullName VARCHAR(100) NULL,
    DOB DATE NULL,
    Gender VARCHAR(20) NULL,
    Address VARCHAR(200) NULL,
    Phone VARCHAR(30) NULL,
    EmailID VARCHAR(100) NULL,
    PersonalEmail VARCHAR(100) NULL, -- Added to match previous OTP functionality
    OfficialEmail VARCHAR(100) NULL,
    BankName VARCHAR(100) NULL,
    BankAccountNo VARCHAR(40) NULL,
    IFSCCode VARCHAR(40) NULL,
    UPPID VARCHAR(100) NULL,
    MaritalStatus VARCHAR(20) NULL,
    Nationality VARCHAR(50) NULL,
    EmploymentType VARCHAR(50) NULL DEFAULT 'Full-time',
    AadharNo VARCHAR(20) NULL,
    PANNo VARCHAR(20) NULL,
    UANNo VARCHAR(20) NULL,
    EmergencyContactName VARCHAR(100) NULL,
    EmergencyContactPhone VARCHAR(30) NULL
);

-- Indexes on Govt ID fields
CREATE UNIQUE INDEX UX_EmployeeDetails_EmailID ON dbo.EmployeeDetails(EmailID) WHERE EmailID IS NOT NULL;
CREATE UNIQUE INDEX UX_EmployeeDetails_UPPID ON dbo.EmployeeDetails(UPPID) WHERE UPPID IS NOT NULL;
CREATE UNIQUE INDEX UX_EmployeeDetails_AadharNo ON dbo.EmployeeDetails(AadharNo) WHERE AadharNo IS NOT NULL;
CREATE UNIQUE INDEX UX_EmployeeDetails_PANNo ON dbo.EmployeeDetails(PANNo) WHERE PANNo IS NOT NULL;
CREATE UNIQUE INDEX UX_EmployeeDetails_UANNo ON dbo.EmployeeDetails(UANNo) WHERE UANNo IS NOT NULL;

-- AdminLogins Table
CREATE TABLE dbo.AdminLogins (
    AppUserID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    Username VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NULL,
    Role VARCHAR(50) NOT NULL CHECK (Role IN ('SuperAdmin', 'HRAdmin', 'PayrollAdmin')),
    LastLogin TIMESTAMP NULL,
    UserStatus VARCHAR(50) NOT NULL DEFAULT 'Active' CHECK (UserStatus IN ('Active', 'Inactive')),
    FailedAttempts INT NOT NULL DEFAULT 0,
    LockoutUntil TIMESTAMP NULL
);

-- EmployeeLogins Table
CREATE TABLE dbo.EmployeeLogins (
    EmployeeUserID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    Username VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NULL,
    LastLogin TIMESTAMP NULL,
    UserStatus VARCHAR(50) NOT NULL DEFAULT 'Active' CHECK (UserStatus IN ('Active', 'Inactive')),
    FailedAttempts INT NOT NULL DEFAULT 0,
    LockoutUntil TIMESTAMP NULL
);

-- 3. CREATE LOGS & TRANSACTION TABLES

-- EmployeeAttendance Table
CREATE TABLE dbo.EmployeeAttendance (
    AttendanceID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    AttendanceDate DATE NOT NULL DEFAULT CURRENT_DATE,
    AttendanceStatus VARCHAR(20) NOT NULL DEFAULT 'Present' CHECK (AttendanceStatus IN ('Present', 'Absent', 'Late', 'Half Day', 'On Leave')),
    CheckInTime TIMESTAMP NULL,
    CheckOutTime DECIMAL(5,2) NULL,
    ClockIn TIME NULL,
    ClockOut TIME NULL,
    TotalHours DECIMAL(5,2) NULL,
    CONSTRAINT UQ_Employee_Attendance_Date UNIQUE (EmpID, AttendanceDate)
);

-- EmployeeLeaveDetails Table
CREATE TABLE dbo.EmployeeLeaveDetails (
    LeaveID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    LeaveType VARCHAR(50) NOT NULL CHECK (LeaveType IN ('Sick Leave', 'Casual Leave', 'Earned Leave', 'Maternity Leave', 'Paternity Leave', 'Unpaid Leave')),
    FromDate DATE NOT NULL,
    ToDate DATE NOT NULL,
    LeaveStatus VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (LeaveStatus IN ('Pending', 'Approved', 'Rejected')),
    LeaveDate DATE NOT NULL DEFAULT CURRENT_DATE,
    LeaveReason VARCHAR(500) NULL,
    LeaveDays INT NULL,
    LeaveStartDate DATE NULL,
    LeaveEndDate DATE NULL,
    TotalDays INT NULL,
    IsPaidLeave VARCHAR(20) NULL,
    EmpStatus VARCHAR(20) NULL,
    ApprovedBy INT NULL REFERENCES dbo.EmployeeMaster(EmpID),
    CONSTRAINT CK_Leave_Dates CHECK (FromDate <= ToDate)
);

-- EmployeeLogDetails Table
CREATE TABLE dbo.EmployeeLogDetails (
    LogID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    LogDate DATE NOT NULL DEFAULT CURRENT_DATE,
    TotalHours DECIMAL(5,2) NULL,
    LoginTime VARCHAR(20) NULL,
    LogoutTime VARCHAR(20) NULL
);

-- SalaryRevisions Table
CREATE TABLE dbo.SalaryRevisions (
    RevisionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    EffectiveDate DATE NOT NULL,
    BasicSalary DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    HouseRentAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    SpecialAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    MedicalAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ConveyanceAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    OtherAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    ProvidentFundPercent DECIMAL(5,2) NOT NULL DEFAULT 12.00,
    ProfessionalTaxPercent DECIMAL(5,2) NOT NULL DEFAULT 0.40,
    TDS DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    Remarks VARCHAR(255) NULL,
    IsActive BOOLEAN NOT NULL DEFAULT TRUE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- EmployeeProfileChangeRequests Table
CREATE TABLE dbo.EmployeeProfileChangeRequests (
    RequestID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    RequestedData TEXT NOT NULL,
    Status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (Status IN ('Pending', 'Approved', 'Rejected')),
    Reason VARCHAR(255) NULL,
    RequestedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ProcessedBy INT NULL REFERENCES dbo.EmployeeMaster(EmpID),
    ProcessedAt TIMESTAMP NULL
);

-- AdminEmployeeMapping Table
CREATE TABLE dbo.AdminEmployeeMapping (
    MappingID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AdminEmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID),
    EmployeeEmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    CONSTRAINT UQ_Admin_Employee UNIQUE (AdminEmpID, EmployeeEmpID)
);

-- EmployeeReporting Table
CREATE TABLE dbo.EmployeeReporting (
    ReportingID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmployeeEmpID INT NOT NULL UNIQUE REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    ManagerEmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID)
);

-- 4. CREATE PAYROLL LIFECYCLE TABLES

-- PayrollRuns Table
CREATE TABLE dbo.PayrollRuns (
    RunID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SalaryMonth INT NOT NULL,
    SalaryYear INT NOT NULL,
    Version INT NOT NULL DEFAULT 1,
    Status VARCHAR(20) NOT NULL DEFAULT 'Draft' CHECK (Status IN ('Draft', 'Reviewed', 'Approved', 'Released')),
    RunDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ApprovedBy INT NULL REFERENCES dbo.EmployeeMaster(EmpID),
    ApprovedDate TIMESTAMP NULL,
    GeneratedBy INT NULL REFERENCES dbo.EmployeeMaster(EmpID), -- Added to support historical data structure
    ReleasedBy INT NULL REFERENCES dbo.EmployeeMaster(EmpID), -- Added to support historical data structure
    ReleasedAt TIMESTAMP NULL, -- Added to support historical data structure
    CONSTRAINT UQ_Payroll_Period_Version UNIQUE (SalaryMonth, SalaryYear, Version)
);

-- PayrollApprovalOtp Table
CREATE TABLE dbo.PayrollApprovalOtp (
    OtpID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RunID INT NULL REFERENCES dbo.PayrollRuns(RunID) ON DELETE CASCADE, -- Made NULLable to support Admin OTP flow
    GeneratedForAdminID INT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE, -- Added to support Admin OTP flow
    OtpCode VARCHAR(10) NOT NULL,
    ExpiresAt TIMESTAMP NOT NULL,
    IsVerified BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- EmployeeSalarysDetails Table
CREATE TABLE dbo.EmployeeSalarysDetails (
    SalaryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    RunID INT NULL REFERENCES dbo.PayrollRuns(RunID) ON DELETE CASCADE,
    DaysPaid INT NOT NULL DEFAULT 30 CHECK (DaysPaid >= 0),
    DaysInMonth INT NOT NULL DEFAULT 30 CHECK (DaysInMonth > 0),
    LossOfPay INT NOT NULL DEFAULT 0 CHECK (LossOfPay >= 0),
    ITPAN VARCHAR(20) NULL,
    SalaryMonth VARCHAR(20) NOT NULL,
    SalaryYear INT NOT NULL,
    BasicSalary DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (BasicSalary >= 0),
    HouseRentAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (HouseRentAllowance >= 0),
    SpecialAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (SpecialAllowance >= 0),
    MedicalAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (MedicalAllowance >= 0),
    ConveyanceAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (ConveyanceAllowance >= 0),
    OtherAllowance DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (OtherAllowance >= 0),
    ProvidentFund DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (ProvidentFund >= 0),
    HealthInsurance DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (HealthInsurance >= 0),
    ProfessionalTax DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (ProfessionalTax >= 0),
    TDS DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (TDS >= 0),
    TotalEarnings DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (TotalEarnings >= 0),
    TotalDeductions DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (TotalDeductions >= 0),
    NetSalaryPaid DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (NetSalaryPaid >= 0),
    PaymentMode VARCHAR(20) NULL,
    TransactionRef VARCHAR(50) NULL,
    PaymentDate DATE NULL,
    PFNo VARCHAR(20) NULL,
    IFSC VARCHAR(20) NULL,
    BankName VARCHAR(100) NULL,
    BankAccountNo VARCHAR(40) NULL,
    CompOffEncashment DECIMAL(10,2) NOT NULL DEFAULT 0.00 CHECK (CompOffEncashment >= 0),
    PaymentStatus VARCHAR(20) NOT NULL DEFAULT 'Unpaid' CHECK (PaymentStatus IN ('Paid', 'Unpaid', 'Processing')),
    CONSTRAINT UQ_Employee_Salary_Period UNIQUE (EmpID, SalaryMonth, SalaryYear, RunID) -- Matches the 03 phase corrections
);

-- PayrollRunSummary Table
CREATE TABLE dbo.PayrollRunSummary (
    SummaryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RunID INT NOT NULL UNIQUE REFERENCES dbo.PayrollRuns(RunID) ON DELETE CASCADE,
    TotalEmployees INT NOT NULL DEFAULT 0,
    EmployeesProcessed INT NOT NULL DEFAULT 0,
    EmployeesSkipped INT NOT NULL DEFAULT 0,
    GrossAmount DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    TotalPF DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    TotalPT DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    TotalTDS DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    TotalLOP DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    NetPayable DECIMAL(18,2) NOT NULL DEFAULT 0.00,
    ExceptionsCount INT NOT NULL DEFAULT 0
);

-- PayslipDispatchLogs Table
CREATE TABLE dbo.PayslipDispatchLogs (
    DispatchID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SalaryID INT NOT NULL REFERENCES dbo.EmployeeSalarysDetails(SalaryID) ON DELETE CASCADE,
    RecipientEmail VARCHAR(100) NOT NULL,
    DispatchStatus VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (DispatchStatus IN ('Pending', 'Sent', 'Failed')),
    ErrorMessage TEXT NULL,
    DispatchedAt TIMESTAMP NULL
);

-- 5. SYSTEM LOGGING & EXTRA SCHEMAS

-- AuditLogs Table
CREATE TABLE dbo.AuditLogs (
    AuditID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ActorEmpID INT NULL REFERENCES dbo.EmployeeMaster(EmpID),
    ActionType VARCHAR(50) NOT NULL,
    ActionDesc VARCHAR(500) NOT NULL,
    ActionTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ImportAuditLogs Table
CREATE TABLE dbo.ImportAuditLogs (
    ImportID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FileType VARCHAR(50) NOT NULL,
    UploadedBy INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID),
    UploadedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TotalRows INT NOT NULL DEFAULT 0,
    SuccessRows INT NOT NULL DEFAULT 0,
    FailedRows INT NOT NULL DEFAULT 0,
    Status VARCHAR(20) NOT NULL DEFAULT 'Success' CHECK (Status IN ('Success', 'Partial', 'Failed'))
);

-- PasswordResetTokens Table
CREATE TABLE dbo.PasswordResetTokens (
    TokenID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    TokenHash VARCHAR(255) NOT NULL,
    ExpiresAt TIMESTAMP NOT NULL,
    IsUsed BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Notifications Table
CREATE TABLE dbo.Notifications (
    NotificationID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    Title VARCHAR(200) NOT NULL,
    Message VARCHAR(500) NOT NULL,
    IsRead BOOLEAN NOT NULL DEFAULT FALSE,
    Category VARCHAR(20) NOT NULL DEFAULT 'System' CHECK (Category IN ('Payroll', 'Leave', 'Profile', 'Attendance', 'System')),
    RelatedID INT NULL,
    CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- EmployeeDocuments Table
CREATE TABLE dbo.EmployeeDocuments (
    DocID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
    DocName VARCHAR(100) NOT NULL,
    DocType VARCHAR(50) NOT NULL,
    FilePath VARCHAR(255) NOT NULL,
    UploadedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Staging Employees Table for CSV Import Validation
CREATE TABLE dbo.Staging_Employees (
    staging_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_session_id UUID NOT NULL,
    raw_legacy_emp_id VARCHAR(100) NULL,
    raw_email VARCHAR(255) NULL,
    raw_first_name VARCHAR(100) NULL,
    raw_last_name VARCHAR(100) NULL,
    raw_designation VARCHAR(100) NULL,
    raw_department VARCHAR(100) NULL,
    raw_join_date VARCHAR(50) NULL,
    raw_phone VARCHAR(50) NULL,
    raw_role VARCHAR(50) NULL,
    validation_status VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (validation_status IN ('Pending', 'Valid', 'Invalid', 'Imported')),
    validation_error TEXT NULL,
    imported_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 6. ADD DEPARTMENTS CIRCULAR REFERENCE FOREIGN KEY
ALTER TABLE dbo.Departments ADD CONSTRAINT FK_Departments_EmployeeMaster FOREIGN KEY (ManagerEmpID) REFERENCES dbo.EmployeeMaster(EmpID);
