import dotenv from 'dotenv';
dotenv.config();

import { connectDB } from '../src/config/db_pg.js';

async function main() {
  console.log('Connecting to PostgreSQL to run migrations...');
  try {
    const pool = await connectDB();
    const req = pool.request();

    console.log('1. Adding IsPayrollEligible column to EmployeeMaster...');
    await req.query(`
      ALTER TABLE dbo.EmployeeMaster 
      ADD COLUMN IF NOT EXISTS IsPayrollEligible BOOLEAN NOT NULL DEFAULT TRUE;
    `);

    console.log('2. Adding Category and RelatedID columns to Notifications...');
    await req.query(`
      ALTER TABLE dbo.Notifications 
      ADD COLUMN IF NOT EXISTS Category VARCHAR(20) NOT NULL DEFAULT 'System';
    `);
    
    await req.query(`
      ALTER TABLE dbo.Notifications 
      ADD COLUMN IF NOT EXISTS RelatedID INT NULL;
    `);

    console.log('3. Adding Check constraint for Category in Notifications...');
    // Drop the constraint if it exists and recreate it to be safe
    try {
      await req.query(`
        ALTER TABLE dbo.Notifications 
        DROP CONSTRAINT IF EXISTS chk_notifications_category;
      `);
      await req.query(`
        ALTER TABLE dbo.Notifications 
        ADD CONSTRAINT chk_notifications_category 
        CHECK (Category IN ('Payroll', 'Leave', 'Profile', 'Attendance', 'System'));
      `);
    } catch (constError) {
      console.warn('Warning when setting constraint (it may already exist):', constError.message);
    }

    console.log('4. Creating PasswordResetTokens table...');
    await req.query(`
      CREATE TABLE IF NOT EXISTS dbo.PasswordResetTokens (
        TokenID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
        TokenHash VARCHAR(255) NOT NULL,
        ExpiresAt TIMESTAMP NOT NULL,
        IsUsed BOOLEAN NOT NULL DEFAULT FALSE,
        CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    `);

    console.log('5. Backfilling category info on Notifications...');
    await req.query(`
      UPDATE dbo.Notifications 
      SET Category = 'Payroll' 
      WHERE (Title ILIKE '%payslip%' OR Title ILIKE '%salary%') AND Category = 'System';
    `);
    await req.query(`
      UPDATE dbo.Notifications 
      SET Category = 'Leave' 
      WHERE Title ILIKE '%leave%' AND Category = 'System';
    `);
    await req.query(`
      UPDATE dbo.Notifications 
      SET Category = 'Profile' 
      WHERE Title ILIKE '%profile%' AND Category = 'System';
    `);

    console.log('6. Adding snapshot columns to EmployeeSalarysDetails...');
    await req.query(`
      ALTER TABLE dbo.EmployeeSalarysDetails 
      ADD COLUMN IF NOT EXISTS EmployeeName VARCHAR(150) NULL,
      ADD COLUMN IF NOT EXISTS Designation VARCHAR(100) NULL,
      ADD COLUMN IF NOT EXISTS Department VARCHAR(100) NULL,
      ADD COLUMN IF NOT EXISTS UANNo VARCHAR(20) NULL,
      ADD COLUMN IF NOT EXISTS AbsentDays INT NOT NULL DEFAULT 0,
      ADD COLUMN IF NOT EXISTS UnpaidLeaveDays INT NOT NULL DEFAULT 0;
    `);

    console.log('7. Creating PayrollRunEmployees table...');
    await req.query(`
      CREATE TABLE IF NOT EXISTS dbo.PayrollRunEmployees (
        RunEmployeeID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        RunID INT NOT NULL REFERENCES dbo.PayrollRuns(RunID) ON DELETE CASCADE,
        EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID),
        SalaryID INT NOT NULL REFERENCES dbo.EmployeeSalarysDetails(SalaryID) ON DELETE CASCADE,
        CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
    `);

    console.log('8. Creating PayrollExceptions table...');
    await req.query(`
      CREATE TABLE IF NOT EXISTS dbo.PayrollExceptions (
        ExceptionID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        RunID INT NOT NULL REFERENCES dbo.PayrollRuns(RunID) ON DELETE CASCADE,
        EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID) ON DELETE CASCADE,
        ExceptionType VARCHAR(50) NOT NULL,
        ExceptionMessage VARCHAR(500) NOT NULL,
        CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ResolvedBy INT NULL REFERENCES dbo.EmployeeMaster(EmpID),
        ResolvedAt TIMESTAMP NULL,
        Status VARCHAR(20) NOT NULL DEFAULT 'Open' CHECK (Status IN ('Open', 'Resolved', 'Ignored'))
      );
    `);

    console.log('9. Recreating PayslipDispatchLogs table...');
    await req.query(`
      DROP TABLE IF EXISTS dbo.PayslipDispatchLogs CASCADE;
      CREATE TABLE dbo.PayslipDispatchLogs (
        DispatchID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        EmpID INT NOT NULL REFERENCES dbo.EmployeeMaster(EmpID),
        SalaryID INT NOT NULL REFERENCES dbo.EmployeeSalarysDetails(SalaryID) ON DELETE CASCADE,
        EmailAddress VARCHAR(100) NOT NULL,
        DispatchStatus VARCHAR(20) NOT NULL DEFAULT 'Pending' CHECK (DispatchStatus IN ('Pending', 'Sent', 'Failed')),
        ErrorMessage TEXT NULL,
        CreatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
        DispatchedAt TIMESTAMP NULL
      );
    `);

    console.log('\n==================================================');
    console.log('[SUCCESS] PostgreSQL DB Migrated Successfully!');
    console.log('==================================================\n');
  } catch (err) {
    console.error('\n[ERROR] Migration failed:', err);
  } finally {
    process.exit(0);
  }
}

main();
